In [12]:
import pandas as pd
df_raw = pd.read_parquet("/gstock/EXOTIC/data/GENOMICS/RefSeq_exons_simple.parquet")
df_raw["Introns_lengths"] = df_raw["Introns_ranges"].apply(lambda r: [int(e.split("-")[1]) - int(e.split("-")[0]) for e in r if int(e.split("-")[1]) - int(e.split("-")[0]) > 0 and int(e.split("-")[1]) - int(e.split("-")[0]) < 2e6])

In [23]:
gene = 'ABCA2'

In [11]:
df_raw.loc[df_raw['Gene'] == gene].to_dict()

{'Gene': {24: 'AASDH'},
 'mRNA_nb_total': {24: 10},
 'Strand': {24: 0},
 'Miso': {24: True},
 'Exons_ranges': {24: array(['57250236-57250465', '57237617-57237809', '57220871-57220977',
         '57220205-57220377', '57217508-57217623', '57213784-57213900',
         '57211293-57211456', '57209728-57209850', '57209001-57209132'],
        dtype=object)},
 'Introns_ranges': {24: array(['57237810-57250235', '57220978-57237616', '57220378-57220870',
         '57217624-57220204', '57213901-57217507', '57211457-57213783',
         '57209851-57211292', '57209133-57209727'], dtype=object)},
 'CDS_count': {24: 9},
 'Introns_lengths': {24: [12425, 16638, 492, 2580, 3606, 2326, 1441, 594]}}

In [24]:
df_raw.loc[df_raw['Gene'] == gene].to_dict()

{'Gene': {34: 'ABCA2'},
 'mRNA_nb_total': {34: 2},
 'Strand': {34: 0},
 'Miso': {34: True},
 'Exons_ranges': {34: array(['139923169-139923324', '139922527-139922592',
         '139918595-139918688', '139918290-139918292',
         '139917393-139917504', '139917154-139917317',
         '139916803-139916930', '139916343-139916453',
         '139915844-139916062', '139915146-139915513',
         '139914788-139914947', '139913630-139913758',
         '139913355-139913522', '139913171-139913267',
         '139912630-139912803', '139912425-139912527',
         '139912239-139912353', '139911954-139912144',
         '139911648-139911798', '139911372-139911576',
         '139911026-139911190', '139910743-139910923',
         '139910414-139910626', '139910127-139910323',
         '139909866-139910048', '139909365-139909549',
         '139909142-139909262', '139908620-139908856',
         '139908284-139908490', '139907913-139908015',
         '139907454-139907770', '139907164-139907377',
         '139906937-139907042', '139906717-139906828',
         '139906554-139906614', '139906296-139906470',
         '139906086-139906201', '139905859-139906006',
         '139905638-139905761', '139905425-139905557',
         '139905072-139905189', '139904645-139904823',
         '139904435-139904576', '139904221-139904355',
         '139903993-139904096', '139903822-139903914',
         '139903403-139903505', '139903183-139903320',
         '139902868-139903074', '139902381-139902416'], dtype=object)},
 'Introns_ranges': {34: array(['139922593-139923168', '139918689-139922526',
         '139918293-139918594', '139917505-139918289',
         '139917318-139917392', '139916931-139917153',
         '139916454-139916802', '139916063-139916342',
         '139915514-139915843', '139914948-139915145',
         '139913759-139914787', '139913523-139913629',
         '139913268-139913354', '139912804-139913170',
         '139912528-139912629', '139912354-139912424',
         '139912145-139912238', '139911799-139911953',
         '139911577-139911647', '139911191-139911371',
         '139910924-139911025', '139910627-139910742',
         '139910324-139910413', '139910049-139910126',
         '139909550-139909865', '139909263-139909364',
         '139908857-139909141', '139908491-139908619',
         '139908016-139908283', '139907771-139907912',
         '139907378-139907453', '139907043-139907163',
         '139906829-139906936', '139906615-139906716',
         '139906471-139906553', '139906202-139906295',
         '139906007-139906085', '139905762-139905858',
         '139905558-139905637', '139905190-139905424',
         '139904824-139905071', '139904577-139904644',
         '139904356-139904434', '139904097-139904220',
         '139903915-139903992', '139903506-139903821',
         '139903321-139903402', '139903075-139903182',
         '139902417-139902867'], dtype=object)},
 'CDS_count': {34: 50},
 'Introns_lengths': {34: [575,
   3837,
   301,
   784,
   74,
   222,
   348,
   279,
   329,
   197,
   1028,
   106,
   86,
   366,
   101,
   70,
   93,
   154,
   70,
   180,
   101,
   115,
   89,
   77,
   315,
   101,
   284,
   128,
   267,
   141,
   75,
   120,
   107,
   101,
   82,
   93,
   78,
   96,
   79,
   234,
   247,
   67,
   78,
   123,
   77,
   315,
   81,
   107,
   450]}}

In [6]:
refseq = pd.read_parquet('/gstock/EXOTIC/data/GENOMICS/refseq_37_processed_cds_variable.parquet')
refseq

,Gene,Exon_type,ranges,mRNA_exons,Exon_start,Exon_stop,Length,Strand,mRNA_exons_nb,mRNA_gene,mRNA_gene_nb,Ratio,Ratio_num,Const_Alt,Share,CDS_count
0,A1BG,CDS,58858388-58858395,[NM_130786],58858388,58858395,7,0,1,[NM_130786],1,1/1,1.0,Const,False,8
1,A1BG,CDS,58858719-58859006,[NM_130786],58858719,58859006,287,0,1,[NM_130786],1,1/1,1.0,Const,False,8
2,A1BG,CDS,58861736-58862017,[NM_130786],58861736,58862017,281,0,1,[NM_130786],1,1/1,1.0,Const,False,8
3,A1BG,CDS,58862757-58863053,[NM_130786],58862757,58863053,296,0,1,[NM_130786],1,1/1,1.0,Const,False,8
4,A1BG,CDS,58863649-58863921,[NM_130786],58863649,58863921,272,0,1,[NM_130786],1,1/1,1.0,Const,False,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213242,ZZZ3,CDS,78047461-78047576,"[NM_001308237, NM_015534]",78047461,78047576,115,0,2,"[NM_015534, NM_001308237]",2,2/2,1.0,Const,False,12
213243,ZZZ3,CDS,78047664-78047811,"[NM_001308237, NM_015534]",78047664,78047811,147,0,2,"[NM_015534, NM_001308237]",2,2/2,1.0,Const,False,12
213244,ZZZ3,CDS,78050202-78050340,"[NM_001308237, NM_015534]",78050202,78050340,138,0,2,"[NM_015534, NM_001308237]",2,2/2,1.0,Const,False,12
213245,ZZZ3,CDS,78097535-78099039,[NM_015534],78097535,78099039,1504,0,1,"[NM_015534, NM_001308237]",2,1/2,0.5,Alt,False,12
213246,ZZZ3,CDS,78105134-78105156,[NM_001308237],78105134,78105156,22,0,1,"[NM_015534, NM_001308237]",2,1/2,0.5,Alt,False,12

In [9]:
refseq.loc[refseq['Gene'] == gene]

,Gene,Exon_type,ranges,mRNA_exons,Exon_start,Exon_stop,Length,Strand,mRNA_exons_nb,mRNA_gene,mRNA_gene_nb,Ratio,Ratio_num,Const_Alt,Share,CDS_count
290,AASDH,CDS,57204568-57204872,"[NM_001286671, NM_001323893, NM_001323892]",57204568,57204872,304,0,3,"[NM_001323892, NM_001286671, NM_181806, NM_001...",10,3/10,0.3,Alt,True,21
291,AASDH,CDS,57204872-57204957,"[NM_001286669, NM_001286668, NM_001286670, NM_...",57204872,57204957,85,0,9,"[NM_001323892, NM_001286671, NM_181806, NM_001...",10,9/10,0.9,Alt,True,21
292,AASDH,CDS,57209001-57209132,"[NM_001286669, NM_001286668, NM_001323893, NM_...",57209001,57209132,131,0,8,"[NM_001323892, NM_001286671, NM_181806, NM_001...",10,8/10,0.8,Alt,False,21
293,AASDH,CDS,57209728-57209850,"[NM_001286669, NM_001286668, NM_001323893, NM_...",57209728,57209850,122,0,8,"[NM_001323892, NM_001286671, NM_181806, NM_001...",10,8/10,0.8,Alt,False,21
294,AASDH,CDS,57211293-57211456,"[NM_001286669, NM_001286668, NM_001286670, NM_...",57211293,57211456,163,0,6,"[NM_001323892, NM_001286671, NM_181806, NM_001...",10,6/10,0.6,Alt,False,21
295,AASDH,CDS,57213784-57213900,[NM_001323890],57213784,57213900,116,0,1,"[NM_001323892, NM_001286671, NM_181806, NM_001...",10,1/10,0.1,Alt,False,21
296,AASDH,CDS,57215391-57215429,"[NM_001286669, NM_001286671, NM_001286668, NM_...",57215391,57215429,38,0,9,"[NM_001323892, NM_001286671, NM_181806, NM_001...",10,9/10,0.9,Alt,True,21
297,AASDH,CDS,57215429-57216224,"[NM_001286672, NM_001286669, NM_001286671, NM_...",57215429,57216224,795,0,10,"[NM_001323892, NM_001286671, NM_181806, NM_001...",10,10/10,1.0,Const,True,21
298,AASDH,CDS,57217508-57217623,"[NM_001286669, NM_001286671, NM_001286668, NM_...",57217508,57217623,115,0,10,"[NM_001323892, NM_001286671, NM_181806, NM_001...",10,10/10,1.0,Const,False,21
299,AASDH,CDS,57219570-57219690,"[NM_001286670, NM_001286669, NM_001286671, NM_...",57219570,57219690,120,0,10,"[NM_001323892, NM_001286671, NM_181806, NM_001...",10,10/10,1.0,Const,True,21
300,AASDH,CDS,57219690-57219762,"[NM_001286669, NM_001286671, NM_001286668, NM_...",57219690,57219762,72,0,9,"[NM_001323892, NM_001286671, NM_181806, NM_001...",10,9/10,0.9,Alt,True,21
301,AASDH,CDS,57220205-57220377,"[NM_001286669, NM_001286671, NM_001286668, NM_...",57220205,57220377,172,0,9,"[NM_001323892, NM_001286671, NM_181806, NM_001...",10,9/10,0.9,Alt,False,21
302,AASDH,CDS,57220871-57220977,"[NM_001286669, NM_001286671, NM_001286668, NM_...",57220871,57220977,106,0,8,"[NM_001323892, NM_001286671, NM_181806, NM_001...",10,8/10,0.8,Alt,False,21
303,AASDH,CDS,57221348-57221426,"[NM_001323899, NM_001286669, NM_001286671, NM_...",57221348,57221426,78,0,9,"[NM_001323892, NM_001286671, NM_181806, NM_001...",10,9/10,0.9,Alt,True,21
304,AASDH,CDS,57221426-57221589,"[NM_001286669, NM_001286671, NM_001286668, NM_...",57221426,57221589,163,0,8,"[NM_001323892, NM_001286671, NM_181806, NM_001...",10,8/10,0.8,Alt,True,21
305,AASDH,CDS,57237617-57237809,"[NM_001286669, NM_001286671, NM_001286668, NM_...",57237617,57237809,192,0,8,"[NM_001323892, NM_001286671, NM_181806, NM_001...",10,8/10,0.8,Alt,False,21
306,AASDH,CDS,57244314-57244522,"[NM_001286669, NM_001323893, NM_001286671, NM_...",57244314,57244522,208,0,8,"[NM_001323892, NM_001286671, NM_181806, NM_001...",10,8/10,0.8,Alt,True,21
307,AASDH,CDS,57244522-57244630,"[NM_001286671, NM_001286668, NM_001323892, NM_...",57244522,57244630,108,0,6,"[NM_001323892, NM_001286671, NM_181806, NM_001...",10,6/10,0.6,Alt,True,21
308,AASDH,CDS,57248643-57248693,"[NM_001286668, NM_001286671, NM_001323892, NM_...",57248643,57248693,50,0,6,"[NM_001323892, NM_001286671, NM_181806, NM_001...",10,6/10,0.6,Alt,True,21
309,AASDH,CDS,57248693-57248763,"[NM_001286671, NM_001323892, NM_181806, NM_001...",57248693,57248763,70,0,5,"[NM_001323892, NM_001286671, NM_181806, NM_001...",10,5/10,0.5,Alt,True,21
310,AASDH,CDS,57250236-57250465,"[NM_001286671, NM_001323892, NM_181806, NM_001...",57250236,57250465,229,0,5,"[NM_001323892, NM_001286671, NM_181806, NM_001...",10,5/10,0.5,Alt,False,21

In [29]:
dext = pd.read_parquet('/gstock/EXOTIC/data/EXOTIC/dext_matrix.parquet')
dext = dext.loc[(dext['dext_up'] > 0.5) | (dext['dext_down'] < - 0.5)]
dext

,Gene,ranges,mRNA_exons,mRNA_nb,Share,Strand,mRNA_gene,mRNA_nb_total,Ratio,Ratio_num,...,Small Intestine - Terminal Ileum,Spleen,Stomach,Testis,Thyroid,Uterus,Vagina,Whole Blood,dext_down,dext_up
11,A2ML1,8995730-8995957,[NM_144670],1,False,1,"[NM_001282424, NM_144670]",2,1/2,0.500000,...,0.116676,0.116676,0.116676,-0.363017,0.116676,-0.179134,0.001128,0.116676,-0.533911,0.116676
12,A2ML1,8997768-8997770,[NM_001282424],1,False,1,"[NM_001282424, NM_144670]",2,1/2,0.500000,...,-0.002816,-0.002816,-0.002816,0.062735,-0.002816,0.624134,-0.002041,-0.002816,-0.010125,0.624134
25,AAK1,69703001-69703095,"[NM_014911, NM_001371575]",2,False,0,"[NM_014911, NM_001371577, NM_001371575]",3,2/3,0.666667,...,-0.007856,-0.006805,-0.013847,-0.039222,-0.018212,-0.010882,-0.006172,-0.024237,-0.114504,0.603078
26,AAK1,69704012-69704116,"[NM_014911, NM_001371575]",2,True,0,"[NM_014911, NM_001371577, NM_001371575]",3,2/3,0.666667,...,-0.007856,-0.006805,-0.013847,-0.039222,-0.018212,-0.010882,-0.006172,-0.024237,-0.114504,0.603078
27,AAK1,69704116-69704122,[NM_014911],1,True,0,"[NM_014911, NM_001371577, NM_001371575]",3,1/3,0.333333,...,-0.007856,-0.006805,-0.013847,-0.039222,-0.018212,-0.010882,-0.006172,-0.024237,-0.114504,0.603078
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31592,ZWILCH,66801179-66801230,[NM_017975],1,False,1,"[NM_017975, NM_001287821]",2,1/2,0.500000,...,0.055885,0.004815,0.421378,-0.027731,-0.003799,-0.030492,0.000018,0.695758,-0.222942,0.695758
31593,ZWILCH,66806326-66806421,[NM_017975],1,False,1,"[NM_017975, NM_001287821]",2,1/2,0.500000,...,0.055885,0.004815,0.421378,-0.027731,-0.003799,-0.030492,0.000018,0.695758,-0.222942,0.695758
31594,ZWILCH,66807864-66807982,[NM_017975],1,False,1,"[NM_017975, NM_001287821]",2,1/2,0.500000,...,0.055885,0.004815,0.421378,-0.027731,-0.003799,-0.030492,0.000018,0.695758,-0.222942,0.695758
31596,ZWINT,58118448-58118485,"[NM_007057, NM_032997]",2,True,0,"[NM_007057, NM_032997, NM_001005413]",3,2/3,0.666667,...,-0.025784,-0.032660,-0.000624,-0.175532,-0.034330,-0.001654,0.002159,0.327792,-0.782071,0.327792
31597,ZWINT,58118566-58118670,[NM_001005413],1,True,0,"[NM_007057, NM_032997, NM_001005413]",3,1/3,0.333333,...,-0.024803,-0.032093,-0.000559,-0.185717,-0.033570,-0.001299,0.002105,0.326503,-0.776965,0.326503

In [30]:
dext.loc[dext['Gene'].str.contains('ADAM22')]

,Gene,ranges,mRNA_exons,mRNA_nb,Share,Strand,mRNA_gene,mRNA_nb_total,Ratio,Ratio_num,...,Small Intestine - Terminal Ileum,Spleen,Stomach,Testis,Thyroid,Uterus,Vagina,Whole Blood,dext_down,dext_up
583,ADAM22,87564341-87564344,"[NM_001324419, NM_001324417]",2,True,1,"[NM_021722, NM_001324417, NM_001324418, NM_016...",6,2/6,0.333333,...,0.010005,0.010005,0.010005,-0.574056,-0.007033,-0.005419,-0.000283,0.010005,-0.574056,0.010005

In [32]:
bbs = ["ARL6", "BBIP1", "BBS1", "BBS10", "BBS12", "BBS2", "BBS4", "BBS5", "BBS7", "BBS9", "C8ORF37", "CEP290", "IFT172", "IFT27", "LZTFL1", "MKKS", "MKS1", "NPHP1", "SDCCAG8", "TRIM32", "TTC8", "WDPCP", ]

In [33]:
dext.loc[dext['Gene'].isin(bbs)]

,Gene,ranges,mRNA_exons,mRNA_nb,Share,Strand,mRNA_gene,mRNA_nb_total,Ratio,Ratio_num,...,Small Intestine - Terminal Ileum,Spleen,Stomach,Testis,Thyroid,Uterus,Vagina,Whole Blood,dext_down,dext_up
3129,BBIP1,112667438-112667594,[NM_001195304],1,False,0,"[NM_001195304, NM_001195307, NM_001195305, NM_...",5,1/5,0.20,...,-0.000129,0.002514,-0.000310,0.750536,-0.000051,-0.001124,0.000326,0.002838,-0.008144,0.750536
29963,WDPCP,63349141-63349191,"[NM_001042692, NM_001354044, NM_015910]",3,False,0,"[NM_001354045, NM_001042692, NM_001354044, NM_...",4,3/4,0.75,...,-0.001104,0.009216,0.002011,-0.002120,0.000199,-0.009491,-0.015141,-0.505740,-0.505740,0.182180
29964,WDPCP,63380049-63380080,"[NM_001042692, NM_001354044, NM_015910]",3,False,0,"[NM_001354045, NM_001042692, NM_001354044, NM_...",4,3/4,0.75,...,-0.001104,0.009216,0.002011,-0.002120,0.000199,-0.009491,-0.015141,-0.505740,-0.505740,0.182180
29965,WDPCP,63380630-63380709,"[NM_001042692, NM_001354044, NM_015910]",3,False,0,"[NM_001354045, NM_001042692, NM_001354044, NM_...",4,3/4,0.75,...,-0.001104,0.009216,0.002011,-0.002120,0.000199,-0.009491,-0.015141,-0.505740,-0.505740,0.182180
29966,WDPCP,63401805-63401967,"[NM_001042692, NM_001354044, NM_015910]",3,False,0,"[NM_001354045, NM_001042692, NM_001354044, NM_...",4,3/4,0.75,...,-0.001104,0.009216,0.002011,-0.002120,0.000199,-0.009491,-0.015141,-0.505740,-0.505740,0.182180
29967,WDPCP,63486442-63486544,"[NM_001042692, NM_001354044, NM_015910]",3,False,0,"[NM_001354045, NM_001042692, NM_001354044, NM_...",4,3/4,0.75,...,-0.001104,0.009216,0.002011,-0.002120,0.000199,-0.009491,-0.015141,-0.505740,-0.505740,0.182180

In [35]:
dext.loc[29963].to_dict()

{'Gene': 'WDPCP',
 'ranges': '63349141-63349191',
 'mRNA_exons': array(['NM_001042692', 'NM_001354044', 'NM_015910'], dtype=object),
 'mRNA_nb': 3,
 'Share': False,
 'Strand': 0,
 'mRNA_gene': array(['NM_001354045', 'NM_001042692', 'NM_001354044', 'NM_015910'],
       dtype=object),
 'mRNA_nb_total': 4,
 'Ratio': '3/4',
 'Ratio_num': 0.75,
 'Const_Alt': 'Alt',
 'Ratio_num_bins': '0.6 - 0.8',
 'Ratio_num_bins_update': '0.6 - 0.8',
 'MAP': 'WDPCP_63349141-63349191',
 'Start': 63349141,
 'End': 63349191,
 'Length': 50,
 'CDS_count': 21,
 'ENSG': 'ENSG00000143951',
 'HGNC': 'HGNC:28027',
 'CHROM': '2',
 'mean_proportion': 0.34734,
 'Adipose - Subcutaneous': 0.0004802966119721308,
 'Adipose - Visceral (Omentum)': 0.020727234966895214,
 'Adrenal Gland': 0.06422969983732485,
 'Artery - Aorta': 2.732336371380484e-06,
 'Artery - Coronary': 0.013813257568751514,
 'Artery - Tibial': -0.006847824921896506,
 'Bladder': 0.07944247830629969,
 'Brain - Amygdala': -0.0004086266968822416,
 'Brain - Anterior cingulate cortex (BA24)': 0.0028390103052953197,
 'Brain - Caudate (basal ganglia)': 0.016743808378300473,
 'Brain - Cerebellar Hemisphere': -0.23651108334164017,
 'Brain - Cerebellum': -0.16341809591653056,
 'Brain - Cortex': 0.0014794216904774338,
 'Brain - Frontal Cortex (BA9)': 0.009131094970849185,
 'Brain - Hippocampus': 0.012256661453580842,
 'Brain - Hypothalamus': 0.02305126641285349,
 'Brain - Nucleus accumbens (basal ganglia)': 0.001163725276510652,
 'Brain - Putamen (basal ganglia)': -0.002010129653070236,
 'Brain - Spinal cord (cervical c-1)': 2.6965304186887806e-05,
 'Brain - Substantia nigra': -0.023275537614664943,
 'Breast - Mammary Tissue': 0.0006563446141452101,
 'Cells - Cultured fibroblasts': 0.03220109694872386,
 'Cells - EBV-transformed lymphocytes': -0.041213849807583025,
 'Cervix - Ectocervix': 0.06602939596568391,
 'Cervix - Endocervix': 0.00021014816902287237,
 'Colon - Sigmoid': -0.00015433918021312554,
 'Colon - Transverse': -0.003956507884781746,
 'Esophagus - Gastroesophageal Junction': 3.510311343801753e-05,
 'Esophagus - Mucosa': 0.002528077438621157,
 'Esophagus - Muscularis': -0.007241593718781636,
 'Fallopian Tube': -0.028994974337524182,
 'Heart - Atrial Appendage': 0.18218021438436804,
 'Heart - Left Ventricle': 0.16643216570854613,
 'Kidney - Cortex': -0.034969007992879386,
 'Liver': -0.025087769478717603,
 'Lung': -6.459213700915623e-05,
 'Minor Salivary Gland': -0.0001494501482803834,
 'Muscle - Skeletal': -0.029493123908370555,
 'Nerve - Tibial': -0.00988611216037305,
 'Ovary': -0.006113542311129816,
 'Pancreas': 0.003379799495064173,
 'Pituitary': 0.03320726047480793,
 'Prostate': 0.004444066586347217,
 'Skin - Not Sun Exposed (Suprapubic)': -0.0014212420952925964,
 'Skin - Sun Exposed (Lower leg)': 2.1469065001555876e-05,
 'Small Intestine - Terminal Ileum': -0.0011040406875101327,
 'Spleen': 0.009215894410424363,
 'Stomach': 0.002011162505039632,
 'Testis': -0.0021196208251356152,
 'Thyroid': 0.00019925169293832923,
 'Uterus': -0.009491239962880038,
 'Vagina': -0.015141026353799436,
 'Whole Blood': -0.5057397838611544,
 'dext_down': -0.5057397838611544,
 'dext_up': 0.18218021438436804}